### ISSUE TITLE
GRUB Display Resolution width and height swapped?

### ISSUE THREAD

**Issue by LetzteFee** [VandalByte/grub-tweaks#13]
This may be unique to my system but for me mentioning the width first works better.
I have a 1080p screen and entered this to my grub config: GRUB_GFXMODE=1080x1920x32. As I rebooted the theme was blurry and not in fullhd. I changed "GRUB_GFXMODE=1080x1920x32" to "GRUB_GFXMODE=1920x1080x32" because you mention the width first in programming. After rebooting the resolution is perfect. 
I think "GRUB_GFXMODE=[height]x[width]x32" has to be "GRUB_GFXMODE=[width]x[height]x32".
It could be because I use linux arch and have weird nvidia drivers. Sorry for my bad english. Anyways, it still helped my to find the right setting.

**Comment by VandalByte** [comment]
Hey @LetzteFee 
Yeah, this ( `GRUB_GFXMODE=[width]x[height]x32` ) is how it should be, I might have missed it, thanks for letting me know. Normally, grub will set it for you during installation, so we don't have to worry about that and this type of error is extremely unlikely.

**Comment by LetzteFee** [comment]
Thank you for fixing ;)
