### ISSUE TITLE
How use grub font generated by grub-mkfont inb your own theme?

### ISSUE THREAD

**Issue by hugo-is-hugo** [VandalByte/grub-tweaks#18]
I have issue to load the pf2 font I have created using grub-mkfont

I tried to follow your steps here to create it:
Creating custom fonts (.pf2) for GRUB] (https://github.com/VandalByte/grub-tweaks#-topics)

I run this command:
`sudo grub-mkfont --output=./DejaVuSansMono28.pf2 --size=28 /usr/share/fonts/TTF/dejavu/DejaVuSansMono.ttf`

on a font that is local already on Ubuntu 24.04 (To make it easy to reproduce and we might use same font).

But when loading it in theme.txt like this. I only see the color take effect, but the theme font is not loaded (I use grub2-theme-preview look it there I see on command line they are loaded.  However not in GUI)
```
+ boot_menu {
    ....
    item_font = "DejaVuSansMono20.pf2"
    item_color = "#919090"
    selected_item_font = "DejaVuSansMono30.pf2""
    selected_item_color = "#ffffff"
    ...
}
```

I saw that you loaded your font like this:
`item_font = "Norwester Regular 28"`

in https://github.com/VandalByte/dedsec-grub2-theme

but the files in the dedsec had format:
```
norwester_24.pf2
norwester_28.pf2
norwester_30.pf2
```

How do you know what name to use in item_font? How do you create it in the font?

**Comment by johan-nilsson-82** [comment]
I found that I need to add `--verbose` flag to see the name to use:

sudo grub-mkfont --output=./DejaVuSansMono28.pf2 --size=28 /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf --verbose

Font name: **DejaVu Sans Mono Regular 28**
Max width: 26
Max height: 34
Font ascent: 28
Font descent: 10
Number of glyph: 3452

the **boldname** I name I use in theme.txt after like: item_font = "DejaVu Sans Regular 28"


Maybe it can updated in your guide? or if you have even a better way of finding the name on already existing fonts.

**Comment by hugo-is-hugo** [comment]
I found the answer my self.

I need to add the `--verbose` flag

`sudo grub-mkfont --output=./DejaVuSansMono30.pf2 --size=30 /usr/share/fonts/truetype/dejavu/DejaVuSans.ttf --verbose`

Font name: **DejaVu Sans Regular 30**
Max width: 48
Max height: 39
Font ascent: 33
Font descent: 12
Number of glyph: 6288

The bold font name in the output is the name that I needed to use in theme.txt for the fonts.

```
+ boot_menu {
    ....
    item_font = "DejaVu Sans Regular 30"
```

Maybe the guide could clarify this step?

**Comment by VandalByte** [comment]
@hugo-is-hugo 

Yeah so the file name has nothing to do with how grub see's the font file, what I usually did was, just put all the fonts that I wanted to test and list all that loaded fonts in grub command line, didn't knew about the verbose tho

If possible, add it to this section and submit a pull request so that others facing the same issue can easily find it or I'll try to add it when I get some free time. Cheers!
https://github.com/VandalByte/grub-tweaks#%EF%B8%8F-creating-custom-fonts-pf2-for-grub
