### ISSUE TITLE
Help with converting a song to it's GRUB tune

### ISSUE THREAD

**Issue by xevilstar** [VandalByte/grub-tweaks#3]
Is there a way to translate on the fly a song into a format that grub can understand ?

**Comment by vandalsoul** [comment]
@xevilstar 
Um no, I don't think so... In my perspective the sound is just there to let the user know that the pc is booting _( longer the tune longer it will take to boot )_
So I don't think there will be much options there for us to do that kinda stuff.

**Comment by xevilstar** [comment]
the idea is about just the first seven notes of a song for example
(I am trying to get something like the first seven notes of command and
conquer's soviet march without success)
https://tabs.ultimate-guitar.com/tab/misc-computer-games/red-alert-soviet-march-chords-3084302
something like ta ta taratta tatta ta taraaaaaaaaa and then boot

**Comment by vandalsoul** [comment]
@xevilstar 
I'm sorry dude, I have zero knowledge about these stuff 😓
I don't think I can help you with this. I'll pin this issue, maybe someone else might be able to help you with this 👍🏼
